[phases.setup]
nixPkgs = [
  "nodejs_22",
  "chromium",
  "glib",
  "nss",
  "atk",
  "cups",
  "dbus",
  "expat",
  "fontconfig",
  "freetype",
  "gtk3",
  "pango",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr"
]

[start]
cmd = "npm start"